/**
 * Global test setup — runs before every test file.
 * Sets required environment variables for the test process.
 */

// Use a known test secret so JWT tokens generated by auth.js helpers
// match what the auth middleware verifies
process.env.JWT_SECRET =
  process.env.JWT_SECRET || "test-jwt-secret-key-for-testing-only-do-not-use-in-production"

process.env.NODE_ENV = "test"
process.env.PORT = "5001"

// Silence morgan HTTP logs during tests
process.env.NODE_ENV = "test"
